spotlight-graphite:
  image: dmrolfs/spotlight-graphite:latest
  expose:
    - 22
    - 2552
  ports:
    - "20004:2004"
  volumes_from:
    - leveldb
  volumes:
    - /Users/rolfsd/spotlight/log:/var/log
    - /Users/rolfsd/spotlight/etc:/etc/spotlight
  environment:
    - SPOTLIGHT_CONFIG=application-prod.conf

data:
  image: gliderlabs/alpine
  command: echo Data Container
  user: 999:999
  labels:
    spotlight.role: "Volume Container"

leveldb:
  extends:
    file: docker-compose.yml
    service: data
  volumes:
    - /Users/rolfsd/spotlight/data/journal:/var/lib/spotlight/data/leveldb/journal
    - /Users/rolfsd/spotlight/data/snapshots:/var/lib/spotlight/data/leveldb/snapshots
